imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"


kizilare_toggl:
  api_url: https://www.toggl.com/api/v8/
  api_key: '%toggl_api_key%'
  workspace_id: '%workspace_id%'
  # Habits to be shown in the schdule
  # - key: minutes from day start
  # - value: Name of the habit
  habits:
    60: Start
    225: Break
    400: Lunch
    540: Coffee
    660: Leave
  # Projects to be detected as valid
  # - key: Name of the project
  # - value: Color to asign on frontent
  projects:
      Meeting: DE7E3D
      System: 4BDE41
